USE [master]
GO

/****** Object:  Database [Ventas]    Script Date: 03/20/2012 16:18:27 ******/
CREATE DATABASE [Ventas] 
GO

ALTER DATABASE [Ventas] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ventas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ventas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ventas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ventas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ventas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ventas] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ventas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ventas] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Ventas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ventas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ventas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ventas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ventas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ventas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ventas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ventas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ventas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ventas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ventas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ventas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ventas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ventas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ventas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ventas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ventas] SET  READ_WRITE 
GO

ALTER DATABASE [Ventas] SET RECOVERY FULL 
GO

ALTER DATABASE [Ventas] SET  MULTI_USER 
GO

ALTER DATABASE [Ventas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ventas] SET DB_CHAINING OFF 
GO


