//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Ventas.Web.ServicioSunat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEmpresa", Namespace="http://tempuri.org/")]
    public partial class Empresas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerEmpresaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Empresas() {
            this.Url = global::Ventas.Web.Properties.Settings.Default.Ventas_Web_ServicioSunat_Empresas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarEmpresaCompletedEventHandler ConsultarEmpresaCompleted;
        
        /// <remarks/>
        public event ObtenerEmpresaCompletedEventHandler ObtenerEmpresaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEmpresa/ConsultarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Ventas.BE")]
        public Empresa[] ConsultarEmpresa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RUC, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombreComercial) {
            object[] results = this.Invoke("ConsultarEmpresa", new object[] {
                        RUC,
                        nombreComercial});
            return ((Empresa[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarEmpresaAsync(string RUC, string nombreComercial) {
            this.ConsultarEmpresaAsync(RUC, nombreComercial, null);
        }
        
        /// <remarks/>
        public void ConsultarEmpresaAsync(string RUC, string nombreComercial, object userState) {
            if ((this.ConsultarEmpresaOperationCompleted == null)) {
                this.ConsultarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarEmpresaOperationCompleted);
            }
            this.InvokeAsync("ConsultarEmpresa", new object[] {
                        RUC,
                        nombreComercial}, this.ConsultarEmpresaOperationCompleted, userState);
        }
        
        private void OnConsultarEmpresaOperationCompleted(object arg) {
            if ((this.ConsultarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarEmpresaCompleted(this, new ConsultarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEmpresa/ObtenerEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Empresa ObtenerEmpresa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RUC) {
            object[] results = this.Invoke("ObtenerEmpresa", new object[] {
                        RUC});
            return ((Empresa)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerEmpresaAsync(string RUC) {
            this.ObtenerEmpresaAsync(RUC, null);
        }
        
        /// <remarks/>
        public void ObtenerEmpresaAsync(string RUC, object userState) {
            if ((this.ObtenerEmpresaOperationCompleted == null)) {
                this.ObtenerEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEmpresaOperationCompleted);
            }
            this.InvokeAsync("ObtenerEmpresa", new object[] {
                        RUC}, this.ObtenerEmpresaOperationCompleted, userState);
        }
        
        private void OnObtenerEmpresaOperationCompleted(object arg) {
            if ((this.ObtenerEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEmpresaCompleted(this, new ObtenerEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Ventas.BE")]
    public partial class Empresa {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string estadoField;
        
        private string rUCField;
        
        private string direccionField;
        
        private string nombrecomercialField;
        
        private string telefonoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrecomercial {
            get {
                return this.nombrecomercialField;
            }
            set {
                this.nombrecomercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultarEmpresaCompletedEventHandler(object sender, ConsultarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerEmpresaCompletedEventHandler(object sender, ObtenerEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591